### ISSUE TITLE
Request to Move Container\Code to the addons folder

### ISSUE THREAD

**Issue by HermanRas** [backwardspy/transit#2]
Hi All,

**SUMERY**
the current location of this repo, is set to root folder instead of addons folder as per the documentation below:
https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html 

**PROBLEM DESCRIPTION**
Using this project from the Godot Asset Store replaces my game's README and add the transit to the top level of my game, instead of the addons folder where its expected

**SOLUTION**
Move project code to ./addons/transit
fix all the res://transit/ links to res://addons/transit
move readme into transit folder
move license into transit folder

![image](https://user-images.githubusercontent.com/38083493/97099127-03367600-168e-11eb-9bf5-243feaa350cc.png)

**Comment by HermanRas** [comment]
I am willing to do all the work and add a PULL request to your repo if that would be easier ?

**Comment by backwardspy** [comment]
Thanks for the report, I will sort that out now.

**Comment by HermanRas** [comment]
Thanks !!
Thanks
Herman Ras
072 520 9364

**Comment by backwardspy** [comment]
I have moved transit into an `addons` folder like you suggested. Instead of moving the repo's README and such into its own folder, I have excluded them from the export archive as suggested here:
https://github.com/vnen/godot-tiled-importer/pull/75
This means the repo still renders nicely in Github's UI, but no extraneous files are downloaded inside Godot itself.
I will write back & close this issue when the change has been accepted on the Godot Asset Library and I can confirm that it works as intended when installing from there.
Thanks again for the issue report!

**Comment by HermanRas** [comment]
sweet, thanks sooo much !
Thanks
Herman Ras
072 520 9364

**Comment by backwardspy** [comment]
@HermanRas Transit 1.1 is live on the asset library and seems to be working nicely. Please give it another try and let me know what you think!

**Comment by HermanRas** [comment]
working 100% on Git  and on Godot Asset Library, a Huge Thanks
